function fig = paper_figure(s)
% PAPER_FIGURE  Create an invisible figure sized in inches for IEEE output.
% Arguments:
%   s  (struct)  paper_style settings struct (uses .width_in, .height_in)
%
% After calling this, build your axes (use paper_axes for styling) and save
% with paper_export.
fig = figure( ...
    'Visible','off', ...
    'Color','w', ...
    'Units','inches', ...
    'Position', [1 1 s.width_in s.height_in], ...
    'PaperUnits','inches', ...
    'PaperSize', [s.width_in s.height_in], ...
    'PaperPositionMode','auto');
end
