function paper_axes(ax, s)
% PAPER_AXES  Configure an axes for IEEE paper output.
% Arguments:
%   ax  (axes handle)                            axes to style in place
%   s   (struct, optional, default paper_style())  paper_style settings struct
%
% White background, black ticks/grid, Times <fontsize> pt, NO title (paper
% captions handle that), TeX interpreter for labels (matches LaTeX maths).
% Call before plotting (it puts the axes in hold-on, grid-on).
if nargin<2, s = paper_style(); end

set(ax, ...
    'Color','w', ...
    'XColor','k', 'YColor','k', ...
    'GridColor', s.gray, 'GridAlpha', 0.3, ...
    'MinorGridColor', s.gray, 'MinorGridAlpha', 0.15, ...
    'Box','on', ...
    'FontName', s.font, 'FontSize', s.fontsize, ...
    'LineWidth', s.lw_axis, ...
    'TickDir','in', ...
    'TickLength',[0.012 0.012], ...
    'TickLabelInterpreter','latex');

% titles go in the figure caption - never on the axes
title(ax,'');

% labels (set/update) - Times font, LaTeX interpreter
set(get(ax,'XLabel'),'Color','k','FontName',s.font,'FontSize',s.fontsize,'Interpreter','latex');
set(get(ax,'YLabel'),'Color','k','FontName',s.font,'FontSize',s.fontsize,'Interpreter','latex');

hold(ax,'on'); grid(ax,'on');
end
